### ISSUE TITLE
Learn to close an issue

### ISSUE THREAD

**Issue by StevenClontz** [clontz-fall-2023/math-visualization-experiments#1]
Hi @NanaTuffour, Issues are a tool on GitHub to point out TODOs for a project.

Your first TODO for this project is to "Close" this issue, letting me know you've seen it. Or reply to let me know if it's not clear how to do that (or if I didn't give you the right permissions to do so).

**Comment by NanaTuffour** [comment]
I don't have the right permissions to close it.

**Comment by StevenClontz** [comment]
Gotcha - should be fixed now?

**Comment by StevenClontz** [comment]
:+1:
